-- Migration: Fix Products, Stock Logs, Projects, Customers & Suppliers RLS & Schema Hardening
-- Target Database: PostgreSQL (Supabase)
-- Date: 2026-09-30
-- Description: Ensures RLS policies and schema integrity for public.products, public.stock_logs,
-- public.projects, public.customers, and public.suppliers to allow authenticated active users (Owner & Kasir)
-- to save and manage master data without authorization failures.

BEGIN;

-- 1. Ensure Table Structure & Audit Columns
CREATE TABLE IF NOT EXISTS public.products (
    id bigint PRIMARY KEY,
    name text NOT NULL,
    category text DEFAULT 'Peralatan Kandang',
    price numeric NOT NULL DEFAULT 0,
    cost_price numeric NOT NULL DEFAULT 0,
    stock numeric NOT NULL DEFAULT 0,
    unit text DEFAULT 'Unit',
    type text DEFAULT 'barang',
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE TABLE IF NOT EXISTS public.stock_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    product_name text,
    action_type text NOT NULL,
    qty numeric NOT NULL DEFAULT 0,
    stock_before numeric NOT NULL DEFAULT 0,
    stock_after numeric NOT NULL DEFAULT 0,
    reference_code text,
    note text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz DEFAULT now()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for public.products
DROP POLICY IF EXISTS p_products_select_authenticated ON public.products;
DROP POLICY IF EXISTS p_products_insert_authenticated ON public.products;
DROP POLICY IF EXISTS p_products_update_authenticated ON public.products;
DROP POLICY IF EXISTS p_products_delete_authenticated ON public.products;

CREATE POLICY p_products_select_authenticated
ON public.products FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

CREATE POLICY p_products_insert_authenticated
ON public.products FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

CREATE POLICY p_products_update_authenticated
ON public.products FOR UPDATE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

CREATE POLICY p_products_delete_authenticated
ON public.products FOR DELETE TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

-- 4. RLS Policies for public.stock_logs
DROP POLICY IF EXISTS p_stock_logs_select_authenticated ON public.stock_logs;
DROP POLICY IF EXISTS p_stock_logs_insert_authenticated ON public.stock_logs;

CREATE POLICY p_stock_logs_select_authenticated
ON public.stock_logs FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

CREATE POLICY p_stock_logs_insert_authenticated
ON public.stock_logs FOR INSERT TO authenticated
WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid() AND profiles.is_active = true
    )
);

-- 5. RLS Policies for public.projects
DROP POLICY IF EXISTS p_projects_select_authenticated ON public.projects;
DROP POLICY IF EXISTS p_projects_insert_authenticated ON public.projects;
DROP POLICY IF EXISTS p_projects_update_authenticated ON public.projects;
DROP POLICY IF EXISTS p_projects_delete_authenticated ON public.projects;

CREATE POLICY p_projects_select_authenticated ON public.projects FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_projects_insert_authenticated ON public.projects FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_projects_update_authenticated ON public.projects FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true)) WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_projects_delete_authenticated ON public.projects FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));

-- 6. RLS Policies for public.customers
DROP POLICY IF EXISTS p_customers_select_authenticated ON public.customers;
DROP POLICY IF EXISTS p_customers_insert_authenticated ON public.customers;
DROP POLICY IF EXISTS p_customers_update_authenticated ON public.customers;
DROP POLICY IF EXISTS p_customers_delete_authenticated ON public.customers;

CREATE POLICY p_customers_select_authenticated ON public.customers FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_customers_insert_authenticated ON public.customers FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_customers_update_authenticated ON public.customers FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true)) WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_customers_delete_authenticated ON public.customers FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));

-- 7. RLS Policies for public.suppliers
DROP POLICY IF EXISTS p_suppliers_select_authenticated ON public.suppliers;
DROP POLICY IF EXISTS p_suppliers_insert_authenticated ON public.suppliers;
DROP POLICY IF EXISTS p_suppliers_update_authenticated ON public.suppliers;
DROP POLICY IF EXISTS p_suppliers_delete_authenticated ON public.suppliers;

CREATE POLICY p_suppliers_select_authenticated ON public.suppliers FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_suppliers_insert_authenticated ON public.suppliers FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_suppliers_update_authenticated ON public.suppliers FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true)) WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));
CREATE POLICY p_suppliers_delete_authenticated ON public.suppliers FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.profiles WHERE profiles.id = auth.uid() AND profiles.is_active = true));

COMMIT;
